import Footer from '@/shared/components/layouts/Footer';
import Header from '@/shared/components/layouts/Header';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function BlogLayout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <Header />
      {children}
      <noscript>
        <iframe
          src="https://www.googletagmanager.com/ns.html?id=GTM-57LHHL2Z"
          height={0}
          width={0}
          style={{ display: 'none', visibility: 'hidden' }}
        />
      </noscript>
      {/* End Google Tag Manager (noscript) */}
      <Footer />
    </>
  );
}
