import Footer from '@/components/layouts/Footer';
import Header from '@/components/layouts/Header';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function BlogLayout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <Header />
      {children}
      <Footer />
    </>
  );
}
