import type { Metadata } from 'next';
import './globals.css';
import localFont from 'next/font/local';
import Header from '@/components/layouts/Header';
import Footer from '@/components/layouts/Footer';
import ProviderTanstack from './provider-tanstack';

// 👈 메이플스토리 폰트만 남기고 나머지 제거
const maplestory = localFont({
  src: [
    {
      path: '../public/font/Maplestory OTF Light.otf',
      weight: '300',
      style: 'normal',
    },
    {
      path: '../public/font/Maplestory OTF Bold.otf',
      weight: '700',
      style: 'normal',
    },
  ],
  variable: '--font-maplestory',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`${maplestory.variable} antialiased`} // 👈 메이플스토리만
        suppressHydrationWarning={true}
      >
        <ProviderTanstack>
          <div className="flex min-h-screen flex-col">
            <Header />
            <main className="flex-1">{children}</main>
            <Footer />
          </div>
        </ProviderTanstack>
      </body>
    </html>
  );
}
