import type { Metadata } from 'next';
import './globals.css';
import localFont from 'next/font/local';
import Header from '@/components/layouts/Header';
import Footer from '@/components/layouts/Footer';
import { ThemeProvider } from '@/components/providers/ThemeProvider';
import TanstackProvider from '../components/providers/TanstackProvider';

const maplestory = localFont({
  src: [
    {
      path: '../public/font/Maplestory OTF Light.otf',
      weight: '300',
      style: 'normal',
    },
    {
      path: '../public/font/Maplestory OTF Bold.otf',
      weight: '700',
      style: 'normal',
    },
  ],
  variable: '--font-maplestory',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={`${maplestory.variable} antialiased`} suppressHydrationWarning={true}>
        <TanstackProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <div className="flex min-h-screen flex-col">
              <Header />
              <main className="flex-1">{children}</main>
              <Footer />
            </div>
          </ThemeProvider>
        </TanstackProvider>
      </body>
    </html>
  );
}
